---
title: "training_fertility intentions"
output: html_document
date: "2024-03-28"
---

```{r setup, include=FALSE}
library(data.table)
library(tidytable)
```


```{r}
train <-fread("C:/Users/lisch/3D Objects/ODISSEI Summer School 2023 - Gert & Lisa/ODISSEI Summer School 2023 - Gert Stulp/1PreFer data for Eyra/1Data for participants/training_data/PreFer_train_data.csv")
train_outcome <- fread("C:/Users/lisch/3D Objects/ODISSEI Summer School 2023 - Gert & Lisa/ODISSEI Summer School 2023 - Gert Stulp/1PreFer data for Eyra/1Data for participants/training_data/PreFer_train_outcome.csv")



```


```{r}

clean_df <- function(df, background_df = NULL){
    # Process the input data to feed the model
  
    # calculate age   
    df$age <- 2024 - df$birthyear_bg

    # Selecting variables for modelling

    keepcols = c('nomem_encr', # ID variable required for predictions,
               'age', 'gender_bg')  # <-------- ADDED VARIABLE 'gender_bg'
  
    # Keeping data with variables selected
    df <- df[ , keepcols ]
    
    # turning gender into factor
    df$gender_bg<- as.factor(df$gender_bg) # <-------- ADDED THIS

    return(df)
}



train_save_model <- function(cleaned_df, outcome_df) {
  # Trains a model using the cleaned dataframe and saves the model to a file.

  # Parameters:
  # cleaned_df (dataframe): The cleaned data from clean_df function to be used for training the model.
  # outcome_df (dataframe): The data with the outcome variable (e.g., from PreFer_train_outcome.csv or PreFer_fake_outcome.csv).

  ## This script contains a bare minimum working example
  set.seed(1) # not useful here because logistic regression deterministic
  
  # Combine cleaned_df and outcome_df
  model_df <- merge(cleaned_df, outcome_df, by = "nomem_encr")
  
  # Logistic regression model
  model <- glm(new_child ~ age + gender_bg, family = "binomial", data = model_df) # <-------- ADDED VARIABLE 'gender_bg'
  
  # Save the model
  saveRDS(model, "model.rds")
}

```

Training the model

```{r}

train_save_model <- function(cleaned_df, outcome_df) {
  # Trains a model using the cleaned dataframe and saves the model to a file.

  # Parameters:
  # cleaned_df (dataframe): The cleaned data from clean_df function to be used for training the model.
  # outcome_df (dataframe): The data with the outcome variable (e.g., from PreFer_train_outcome.csv or PreFer_fake_outcome.csv).

  ## This script contains a bare minimum working example
  set.seed(1) # not useful here because logistic regression deterministic
  
  # Combine cleaned_df and outcome_df
  model_df <- merge(cleaned_df, outcome_df, by = "nomem_encr")
  
  # Logistic regression model
  model <- glm(new_child ~ partner_2020 + I(age^2) + oplmet_2020, family = "binomial", data = model_df)
  
  # Save the model
  saveRDS(model, "model.rds")
}

train_save_model(clean_df(train), train_outcome)


```


Evaluating on test set
```{r}
predict_outcomes <- function(df, background_df = NULL, model_path = "./model.rds"){
  # Generate predictions using the saved model and the input dataframe.
    
  # The predict_outcomes function accepts a dataframe as an argument
  # and returns a new dataframe with two columns: nomem_encr and
  # prediction. The nomem_encr column in the new dataframe replicates the
  # corresponding column from the input dataframe The prediction
  # column contains predictions for each corresponding nomem_encr. Each
  # prediction is represented as a binary value: '0' indicates that the
  # individual did not have a child during 2021-2023, while '1' implies that
  # they did.
  
  # Parameters:
  # df (dataframe): The data dataframe for which predictions are to be made.
  # background_df (dataframe): The background data dataframe for which predictions are to be made.
  # model_path (str): The path to the saved model file (which is the output of training.R).

  # Returns:
  # dataframe: A dataframe containing the identifiers and their corresponding predictions.
  
  ## This script contains a bare minimum working example
  if( !("nomem_encr" %in% colnames(df)) ) {
    warning("The identifier variable 'nomem_encr' should be in the dataset")
  }

  # Load the model
  model <- readRDS(model_path)
    
  # Preprocess the fake / holdout data
  df <- clean_df(df, background_df)

  # Exclude the variable nomem_encr if this variable is NOT in your model
  vars_without_id <- colnames(df)[colnames(df) != "nomem_encr"]
  
  # Generate predictions from model
  predictions <- predict(model, 
                         subset(df, select = vars_without_id), 
                         type = "response") 
  
  # Create predictions that should be 0s and 1s rather than, e.g., probabilities
  predictions <- ifelse(predictions > 0.5, 1, 0)  
  
  # Output file should be data.frame with two columns, nomem_encr and predictions
  df_predict <- data.frame("nomem_encr" = df[ , "nomem_encr" ], "prediction" = predictions)
  # Force columnnames (overrides names that may be given by `predict`)
  names(df_predict) <- c("nomem_encr", "prediction") 
  
  # Return only dataset with predictions and identifier
  return( df_predict )
}

pred <- predict_outcomes(test)


score <- function(y_true, y_pred){
    #Score (evaluate) the predictions. This function takes a vector containing predicted outcomes and a vector containing the ground truth outcomes.      It calculates the overall prediction accuracy, and precision, recall, and F1 score for having a child and returns a data frame with these values.
    # Calculate accuracy
    accuracy <- sum(y_true == y_pred)/length(y_true)

    # Calculate true positives, false positives, and false negatives
    true_positives <- sum((y_true == 1) & (y_pred == 1))
    false_positives <- sum((y_true == 0) & (y_pred == 1))
    false_negatives <- sum((y_true == 1) & (y_pred == 0))
    
    # Calculate precision, recall, and F1 score
 
    precision = true_positives / (true_positives + false_positives)  # returns NaN if both true positives and false positives = 0
    recall = true_positives / (true_positives + false_negatives)  # returns NaN if both true positives and false negatives = 0 (e.g. only in case there are no positive cases)
    f1_score = 2 * (precision * recall) / (precision + recall) # returns NaN of precision or recall are not defined
   
    
    
    metrics_df <- data.frame(
        'accuracy'=accuracy,
        'precision'=precision,
        'recall'=recall,
        'f1_score'=f1_score
    )
    
    return(metrics_df)

}


score(test_outcome$new_child, pred$prediction) # f1_score NaN

```